services:
  backend:
    build: ./backend
    container_name: ferreteria-backend
    ports:
      - "4000:4000"
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ferreteria-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ferreteria_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: